### ISSUE TITLE
Crash upon changing the wallpaper

### ISSUE THREAD

**Issue by Quantenzitrone** [Bnyro/WallYou#10]
wall you crashes frequently on my Phone
- when i try to apply wallpapers (not always)
- in the Background when automatic wallpaper changing is acive (probably the same issue as 1)

My system:

OS: Android 8.1.0 aarch64
Host: SHIFT SHIFT6m
Kernel: 3.18.60-SHIFT
CPU: AArch64 rev 4 (aarch64) (7)

_yes this is copied from neofetch_

**Comment by Quantenzitrone** [comment]
how can i access error logs?

**Comment by Bnyro** [comment]
I'd recommend  [Scoop](https://github.com/TacoTheDank/Scoop) if your phone is rooted, else I'd recommend following the tutorial [here]( https://forum.xda-developers.com/t/tutorial-how-to-logcat.1726238/).

**Comment by Ilithy** [comment]
Scoop is excellent, I use it on my device, for info (just in case) It is quite possible to use scoop on a smartphone not rooting via [adb](https://github.com/TacoTheDank/Scoop/wiki#instructions-for-non-rooted-users)

I don't have these problems, WallYou has been running for a few days without problems 🤩

 _(Pixel 6 pro under grapheneos/android 13, battery management of the app set to optimized)_

**Comment by Bnyro** [comment]
>  _(Pixel 6 pro under grapheneos/android 13, battery management of the app set to optimized)_
>
Does the auto-changer work in optimized battery mode as well? I made the experience that the `WorkManager` for background tasks works very inconsistent in that mode sometimes (at least when being in battery saver mode).

**Comment by Ilithy** [comment]
> Does the auto-changer work in optimized battery mode as well? I made the experience that the WorkManager for background tasks works very inconsistent in that mode sometimes (at least when being in battery saver mode).

it works well, sometimes the change of wallpaper occurs when I turn on the screen / use the device _(probably frozen in the background, then unfrozen)_, on the other hand, **it is without the battery saver mode** _(I do not use)_

**Comment by Quantenzitrone** [comment]
```
FATAL EXCEPTION: Thread-20
Process: com.bnyro.wallpaper, PID: 21907
java.lang.IllegalArgumentException: x must be >= 0
	at android.graphics.Bitmap.checkXYSign(Bitmap.java:408)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:781)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:750)
	at c5.e.run(SourceFile:119)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by Bnyro** [comment]
Hmm, tested but can't reproduce. I just noticed that just nothing happens when trying to reapply a wallpaper but at least it didn't crash. The error log means that the image had a width of 0 pixels which is sorta weird.

**Comment by Quantenzitrone** [comment]
that's certainly weird

**Comment by Bnyro** [comment]
In theory we can try to use the absolute value of the negative width, it might be mirrored at the y axis then but at least it's worth a try :joy:

**Comment by Bnyro** [comment]
Do you have cropping the image enabled?

**Comment by Quantenzitrone** [comment]
no i had not enabled it but enabling it fixes the crashing

**Comment by Bnyro** [comment]
Oh, okay, thanks for testing, then I know where to have a look at!
