### ISSUE TITLE
Crop image not for lockscreen

### ISSUE THREAD

**Issue by Tealk** [Bnyro/WallYou#100]
### Steps to reproduce

Enable Wallpaper target both
Activate crop images
Background is set automatically by app
wait until background is changed

### Expected behavior

Background is displayed centered

### Actual behavior

Background is not displayed centered in the lock screen only in the homescreen

### Wall You version

3.3(17)

### Android version

GraphenOS 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The wallpaper is applied exactly the same way for lock screen and home screen. If it's not displayed properly, that's an issue of the ROM and not the app.
Can't reproduce on LineageOS.

**Comment by Tealk** [comment]
But this is strange, images without the option are displayed correctly and images from the gallery too
