### ISSUE TITLE
[Feature] Preview possible Material You color

### ISSUE THREAD

**Issue by NeeRaj-2401** [Bnyro/WallYou#16]
As in Android 12 and later
System UI generates a color and applies as a theme

WallYou should provide some possible material You colors of each wallpaper 
That can be generated after applying to wallpaper 

It will be helpful to predict the possibility of themes after applying as wallpaper

**Comment by NeeRaj-2401** [comment]
Something like this
<img src="https://user-images.githubusercontent.com/88180887/205131091-bce0a17b-1a9b-4dbc-a58e-51296cbde431.png" width="35%" >

**Comment by Bnyro** [comment]
That actually looks quite possible, there is an official [Android library](https://developer.android.com/develop/ui/views/graphics/palette-colors) for it :)
