### ISSUE TITLE
Favorite exception filter

### ISSUE THREAD

**Issue by Tealk** [Bnyro/WallYou#18]
Hello,

thanks for the great app.
But it would help a lot if you can not only search by keywords but also filter out.
So it would be easier to get the wallpapers you really like.

**Comment by Bnyro** [comment]
Wallhaven supports that and thus it's possible for it, Picsum doesn't support any filters unfortunately.

**Comment by Tealk** [comment]
How do I do it then?
I have the filter button at the bottom right and then I can add filters at the top. But when I add filters there, I only search for those terms.

For example if I search for space but don't want spaceships I would add a fromel: + space -spaceship

**Comment by Bnyro** [comment]
I meant the API supports it, Wall You doesn't support it yet so you'll need to wait until I add support for it.

**Comment by Bnyro** [comment]
Though, when you add a search filter like `-spaceship`, doesn't it already exclude all those results with a spaceship? I wonder how much sense it would make to add an extra option for that.

**Comment by Tealk** [comment]
> Though, when you add a search filter like `-spaceship`, doesn't it already exclude all those results with a spaceship?

I didn't come up with the idea, but it doesn't seem to work.

**Comment by Bnyro** [comment]
That's weird, according to their [API documentation](https://wallhaven.cc/help/api) it should somewhat work like that, I've tried the corresponding request to your example, which would be https://wallhaven.cc/api/v1/search?q=space%20-spaceship and it somewhat seems to filter out spaceships, at least the response differs from https://wallhaven.cc/api/v1/search?q=space.

**Comment by Tealk** [comment]
Thanks for the support

i guess i have to have a look at the website and what tags the pictures have that i like
is probably not quite intuitive
