### ISSUE TITLE
IzzyOnDroid inclusion

### ISSUE THREAD

**Issue by Bnyro** [Bnyro/WallYou#2]
Hey @IzzySoft,
sorry to bother you once again, you can probably already guess what it's about ;)

It would be great if WallYou could join the collection of apps at your repo :)
The app uses the Wallhaven API at the moment which is non-free, therefore it'll need to get the `NonFreeNet` anti-feature.

The fastlane structure should already be set up, screenshots will follow too one day probably :wink:
I'm not really planning to add changelogs as I tend to forget it most time, so better skipping that this time.
Last but not least, the `full_description.txt` will need to change too one day, I'll improve that too soon maybe 😄 

Cheers and thanks in advance

**Comment by IzzySoft** [comment]
I usually do not pick wallpaper apps – but how could I resist when asked this way? :rofl: Just added, will become available with the next sync.

However, your Fastlane needs some adjustments. Short Description must be plain ASCII, no HTML tags allowed. And the full desc should be a bit more detailed. Suggestions:

`short_description.txt`: "Wallpaper app built with Material Design 3 (You)"

`full_description.txt`:

```markdown
<i>Wall You</i> is a Wallpaper App built with <a href='https://m3.material.io/'>Material Design 3 (You)</a>. The app uses the Wallhaven API at the moment which unfortunately is non-free.

<br><b>Features:</b>

* Material Design 3 (You)
* Dark and light theme
* Entirely Open Source
* Written in Jetpack Compose
```

> screenshots will follow too one day probably

Very welcome! Please give me a ping once they're there, so I adjust the config here accordingly.

**Comment by Bnyro** [comment]
> I usually do not pick wallpaper apps – but how could I resist when asked this way? 🤣 Just added, will become available with the next sync.
> 
Awesome, thank you for making an exception for WY :)
What's the issue with Wallpaper apps though, are there so many? :joy:
> However, your Fastlane needs some adjustments. Short Description must be plain ASCII, no HTML tags allowed. And the full desc should be a bit more detailed. Suggestions:
> 
I've updated them accordingly, thank you for having a look at them :)

Thank you for your efforts, I'm very pleased to have yet another app living in your repo :wink:

**Comment by IzzySoft** [comment]
> What's the issue with Wallpaper apps though, are there so many?

I don't dare saying to the developer of one :see_no_evil: It's rather a personal preference. The repo runs on my personal resources, so I try focusing on what I would consider "practical things". Having the wallpaper replaced in whatever intervals simply doesn't sound important enough **to me**, so I don't add such apps just when encountering them. They however might perfectly fit the inclusion criteria I've set up, so I have no issues making an exception when explicitly asked for (especially if that "someone" is a developer already having some apps in my repo :smile:).

Thanks for updating the fastlane files! I've updated my config accordingly to check them for updates. In case I didn't yet mention them: I've set up [some formatting hints for `full_description.txt`](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) you might wish to take a look at, for future edits :smiley:

> Thank you for your efforts

Gladly done – and thanks for yours!

**Comment by Bnyro** [comment]
> I don't dare saying to the developer of one 🙈 It's rather a personal preference. The repo runs on my personal resources, so I try focusing on what I would consider "practical things". Having the wallpaper replaced in whatever intervals simply doesn't sound important enough **to me**, so I don't add such apps just when encountering them. They however might perfectly fit the inclusion criteria I've set up, so I have no issues making an exception when explicitly asked for (especially if that "someone" is a developer already having some apps in my repo 😄).
> 
Haha, I felt about the same concerning random wallpapers before the dynamic colors were introduced with Android 12. After I upgraded my ROM I spent way too much time searching good wallpaper apps to get surprised with new dynamic colors each day. Because I couldn't find one that's really working good, I decided to quickly create my one :wink:
However, it's great to almost have a monopoly at your repo, thank you for that one :rofl:

> Thanks for updating the fastlane files! I've updated my config accordingly to check them for updates. In case I didn't yet mention them: I've set up [some formatting hints for `full_description.txt`](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) you might wish to take a look at, for future edits 😃
> 
You already sent me those twice before but I tend to just forget about them and do just what comes into my mind (which sucks usually :joy: ), I'll have a look at them again, thanks <3
