### ISSUE TITLE
Purity setting on sketchy 

### ISSUE THREAD

**Issue by IamHaddad** [Bnyro/WallYou#3]
Hi 
When i set the Purity to sketchy nothing loads in the screen
I'm not sure if it's an app problem or the API problem
I got the app from fdroid

**Comment by vodkapmp** [comment]
Did you change the category at the same time?
The general category doesn't have any matches for sketchy purity.

**Comment by Bnyro** [comment]
> Did you change the category at the same time? Or remove the default filters? 
> The general category doesn't have any matches for sketchy purity due to the default filters set in the app.
> ![IMG_20221024_065253](https://user-images.githubusercontent.com/70449815/197451039-f4744f94-fcf0-4bd5-b0d0-44dbfce1c45b.jpg)
> 

That's probably it, thanks for having a look at that :)

**Comment by IamHaddad** [comment]
Thanks
I didnt know about that
