### ISSUE TITLE
App Crashes when setting any OWalls wallpaper

### ISSUE THREAD

**Issue by JatinKumarKushwaha** [Bnyro/WallYou#32]
Title basically, the apps crashes when trying to set any OWalls wallpaper through the app, you can download them just fine. Also some of the OWalls wallpapers are repeated.

Don't know what's causing it.

Device: gram
Android Version: 12
App Version: 2.3

**Comment by JatinKumarKushwaha** [comment]
Ok, so it doesn't happen with all the images.

Here's what the error says
![Screenshot_2023-01-13-01-55-35-644_com miui bugreport](https://user-images.githubusercontent.com/97663091
/212174281-00e39f0e-eb5e-485e-bdb3-123f9fea3c81.jpg)

**Comment by JatinKumarKushwaha** [comment]
Ok, so it doesn't happen with all the images.

Here's what the error says:

![Screenshot_2023-01-13-01-55-35-644_com miui bugreport](https://user-images.githubusercontent.com/97663091/212174560-e733a2d5-f587-4e27-aedb-64062aa7ab44.jpg)

**Comment by Bnyro** [comment]
Oh well, looks like #10 is back again.
It would be awesome if you could share a way to find wallpapers that crash for me to be able to reproduce it!

**Comment by JatinKumarKushwaha** [comment]
Here's a wallpaper,

![Screenshot_2023-01-13-15-36-16-672_com bnyro wallpaper](https://user-images.githubusercontent.com/97663091/212293841-74b5a868-3256-4913-996f-c4b63d6aa202.jpg)

![Screenshot_2023-01-13-15-34-04-857_com bnyro wallpaper](https://user-images.githubusercontent.com/97663091/212293878-acd83240-c96f-447c-b8e6-468c919b313d.jpg)

**Comment by Bnyro** [comment]
About the repeated wallpapers from OWalls: I can't do anything about that as they're all located at different URLs, so there's no way for the app to figure out whether some wallpapers get returned duplicated.

**Comment by JatinKumarKushwaha** [comment]
Eh, it's fine. Thanks for the fix.
