### ISSUE TITLE
[Enhancement] F-Droid change log

### ISSUE THREAD

**Issue by ae5960e8-a6fc-491f-b252-898ecf59af95** [Bnyro/WallYou#33]
When an update is released we need to check the GitHub repo to see the chang log. F-Droid has a section which shows the change log which is quicker and easier to access, I think it would be better if you took advantage of this feature.

**Comment by Bnyro** [comment]
I'm aware of that and already provide changelogs for two other apps on F-Droid, however I don't really like adding it manually before each release and thus decided to not do it for Wall You.
