### ISSUE TITLE
Is there an option to disable automatic wallpaper changer

### ISSUE THREAD

**Issue by Moxville** [Bnyro/WallYou#34]
Thanks for the nice app.
moto g82 5g
Android 12
wallyou 2.4

I prefer to manually select a wallpaper and set it.
But once I install the App, my wallpaper was changed automatically (not sure why)
I have not enabled "wallpaper changer" option

An option to disable automatic wallpaper changer would be nice.

**Comment by Bnyro** [comment]
There's an option for it, click the 3 horizontal strokes on the top left, then navigate to settings and disable the "wallpaper changer" with the checkbox there.
I just made sure the option works fine and it does, so there should be nothing changing the wallpaper automatically when disabling it.
