### ISSUE TITLE
fix navigation drawer indicator 

### ISSUE THREAD

**Issue by sakshiagrwal** [Bnyro/WallYou#38]
right now in WallHaven section but it shows Picsum
![Screenshot_20230120-051328_Wall You](https://user-images.githubusercontent.com/81718060/213586803-833eaac4-5fa6-466a-bc37-7316bcb5fc96.png)

**Comment by Bnyro** [comment]
Can't reproduce.

**Comment by sakshiagrwal** [comment]
Steps to reproduce
- Open **WallHaven** app
- Then open any section from the navigation drawer, for example **OWalls**
- Now close the app
- So next time whenever we open the app then by default **WallHaven** section will be open. But in the navigation drawer it's still shows **OWalls** section

Version
2.5
