### ISSUE TITLE
Folder for local wallpapers

### ISSUE THREAD

**Issue by MichalisSak** [Bnyro/WallYou#53]
### Describe your suggested feature

It would be nice, if there was an option to have a whole folder for auto applying local wallpapers, instead of selecting them every time.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's not planned since it would require adding storage permissions to the app. Using local wallpapers is only a small side feature and thus isn't worth adding the permissions only for that.

**Comment by Bnyro** [comment]
However, you can move your images to `Android/data/com.bnyro.wallpaper/images/` manually if you want to.

**Comment by Bnyro** [comment]
I found a way to implement this now, will be available with the next update :)
