### ISSUE TITLE
New source Request: Add wallpaper.mob.org

### ISSUE THREAD

**Issue by rozari0** [Bnyro/WallYou#61]
### Describe your suggested feature

https://wallpaper.mob.org has really cool collection of wallpaper. It would be great if I can use this as a wallpaper source in WallYou. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
They don't seem to have a public API, I will try to figure out about it due to the network requests made by JS, but if there's no real API I don't want to add it as it would require to do web scraping which would require adding additional dependencies to the app and might be breaking easily.

**Comment by Bnyro** [comment]
Unfortunately, the site has no public API and thus there are no plans to add it.
