### ISSUE TITLE
Foreground service

### ISSUE THREAD

**Issue by ygorigor** [Bnyro/WallYou#62]
### Describe your suggested feature

Add please a foreground service that will keep app running.

### Other details

On my phone the app is stopping after some time and wallpaper is not changing anymore.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
That's a bad idea for our use case. Instead, disable battery optimizations for the app.
