### ISSUE TITLE
Feature Request: Quality of applied wallpapers

### ISSUE THREAD

**Issue by KR4U7H3R** [Bnyro/WallYou#64]
### Describe your suggested feature

Hey, thanks for the awesome app.

Edit: i realized that the first problem was a mistake on my end.

But what I did realize is that the quality of the wallpapers is a bit worse than the original one. So if I set the (offline) wallpaper with my Gallery app it looks sharper. Is there always a slight blur filter activated? I saw that the Blur filter is always at 1. Does 1 equal deactivated?

Regards 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The title should probably be "Disable Blur"?
And yes, 1 equals to blur being disabled.

**Comment by KR4U7H3R** [comment]
Yes thanks, I forgot to change the Titel.

But the problem still exists. Here are some screenshots of the same file

![Wall You](https://user-images.githubusercontent.com/117851447/222435575-12245a5e-bc2d-4536-8abd-fe3363c1b6dd.jpg)
Wall You
![Gallery App (Aves Libre)](https://user-images.githubusercontent.com/117851447/222435581-8bbbedff-8fce-4ea4-939c-ab6e01bf91c6.jpg)
Gallery App (Aves Libre)

**Comment by Bnyro** [comment]
Thanks for the screenshots, I might know what's going on and will push a potential fix later!

**Comment by KR4U7H3R** [comment]
It might have improved with the last update. But the quality is still worse than the one of the gallery app. It looks more pixelated. I can upload more screenshots if necessary.

**Comment by KR4U7H3R** [comment]
![Screenshot_2023-03-22-12-19-37-922_com saggitt omega-edit](https://user-images.githubusercontent.com/117851447/227192135-f2e61d86-6687-4bcb-bbea-226cc41da0ac.jpg)
WallYou
![Screenshot_2023-03-22-12-20-35-448_com saggitt omega-edit](https://user-images.githubusercontent.com/117851447/227192152-1fb01203-d9e2-47e7-a85e-fe01ffb9ffe4.jpg)
Gallery App
