### ISSUE TITLE
[New Source] Alpha Coders

### ISSUE THREAD

**Issue by Heus-Sueh** [Bnyro/WallYou#66]
### Describe your suggested feature

https://mobile.alphacoders.com/

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Unfortunately, the site has no public API and thus there are no plans to add it.
