### ISSUE TITLE
Hi!! I can help you achieve the material drawer that overlays the statusbar without a shadow 

### ISSUE THREAD

**Issue by HiFIi** [Bnyro/WallYou#7]
First and foremost, hello and thank you for your hard work. I am actually super excited at the thought of being able to help and thus am feeling vulnerable so if you're not interested I kindly ask you be gentle about it if that's ok? 😂

Anyways I was fooling around for multiple hours trying to get it to work and I finally achieved the ability to overlay the drawer over everything, including the statusbar without a shadow !! It was awesome when I finally got it

I didn't want to spend possibly hours of work to submit a pull request you weren't interested in but I have the code I can send you or I can attempt to do it myself if you approve

Thank you so much for your time and again, excited hopefully at the opportunity to improve this gorgeous app. Thanks!

- hifii

**Comment by HiFIi** [comment]
I can't post pics but here is the screenshot: https://photos.app.goo.gl/hWJEzQHEkj6MXjEn8

**Comment by Bnyro** [comment]
Hey,
first of all thanks for your interest in the app and contributing to it, I do really appreciate that!

Concerning the toolbar, there are two major questions I have concerning it:
1. Would it require adding e.g. a third party library?
2. Can it be made an option easily?

As material design 3 toolbars don't come without the shadow by default, I at least don't want to force any users to use it like that, but having it as an additional customization would be quite cool. As I'm on vacation for this week, I won't work on it but if you want to create a PR adding an option (without a 3rd party library) I would be pleased to merge that :)

Cheers

**Comment by HiFIi** [comment]
Hi! Thanks for your response sorry it took me 17 hours to reply. Here are the libraries it uses!! They're all Google ones. Here's https://photos.app.goo.gl/8sgWYL8iBfPQSQsU8

Anyways please view that and let me know if you're interested, id say it can be easily made an option because iirc (it's been a few years since I have coded to be honest I only know java) but the drawer is highly modular and customizable!  

Please respond when you can, hope you're enjoying your vacation

- Kyler (hifii)

**Comment by Ilithy** [comment]
if i can ask a question...
`com.android.gms:play-service-location`
is this really necessary?

Thanks

**Comment by Bnyro** [comment]
> Hi! Thanks for your response sorry it took me 17 hours to reply. Here are the libraries it uses!! They're all Google ones. Here's https://photos.app.goo.gl/8sgWYL8iBfPQSQsU8
> 
Hey, thanks for your response!

I just realized the libraries you used are the old ones being based on writing layout files in XML. However, Wall You uses a new "design framework" by Google (foss) called `Jetpack Compose` which allows to write the layout as composable functions written as code in Java (or Kotlin in our case), so your implementation is not compatible with Wall You as it doesn't use traditional XML layout files anymore.

So to sum up, it would probably require us to write a new imolementation of that, but in Jetpack Compose which wouldn't be really worth it I guess, therefore I'll close the issue for now.

> hope you're enjoying your vacation
>
Thanks, enjoyed most of it so far :)

Anyways thanks for your efforts <3

Cheers

**Comment by HiFIi** [comment]
Yep! Makes sense. This is exactly why I didn't attempt to try it

Btw the gms location thing was just something I was testing for me, it's been a while since I coded so it wouldn't surprise me if I was using old stuff, i also made the app on the app called AndroidIDE

Sucks it would require so much work but at least I tried. Thanks!!
