### ISSUE TITLE
Customize large images

### ISSUE THREAD

**Issue by Tealk** [Bnyro/WallYou#72]
### Describe your suggested feature

When large images are automatically set as backgrounds, they always start at the top left of the image.
Would it be possible to add an option if the image should be centered or similar?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
Enable "Crop images" in the settings.
