### ISSUE TITLE
Playstore release

### ISSUE THREAD

**Issue by MF-Debug** [Bnyro/WallYou#78]
### Describe your suggested feature

As the title says, is there any plan for this app to be published on playstore?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
No, I don't plan to publish any of my apps on the play store.
